config:
  aws:region: us-east-1
  nodejs-microsservices-challenge:orders_database_url:
    secure: AAABAFw6vCfHpmWZwN6P6HuIfbugUFk8ewrhZ+RQ/0wFQAuXhY+D8fwegmBGf0D4K7CeC2gu0Ns2jcyMUerC/w0+imFjKThOfZFxc0eIPNSzIjHZRiabNOwcWrq305QxOOeOh/qtNVKUqqoonHqLs+m1TlU0mWLCkdf0AXhSvCMRdE5hcS5LHLUWl6djP4DeGKFPUm+unjxGcpagIqekKLVHfAEkjiS8w1qyJA==
  nodejs-microsservices-challenge:invoices_database_url:
    secure: AAABADrO2zx7kCubJvDmiRasCZSbtG5RyFtl3RCuyyk0djD+P1UwWeL1Nov8EPaMRN+LQDZhUVsRjYgCNlTC0snTTp5bufTgeYIMNekwd9pTUL4bweRuO8sBZ54Qfq6JlzfFCkCag7kh8uy7lAqn6LDNA2aJf0Lt1uxQ4LItGCcx6DvOixmGlB57s/0TNHq1M/69w72Qslp1IGBqhenCmiCWGPdHwwhxzzJmjw==
  nodejs-microsservices-challenge:orders_grafana_headers:
    secure: AAABAJK0MqfpKlqha4Za3xwp8PG/CxpI8uZxE8dtw3O0VsIJtzVxMUz82OdvYIJGEs4Uhb/KLnNtkKiXVb4MN5VufzmBTBy9l/ZlJkKkM+nTEEFxDwMp3AzA7TwYgPtWE3eq7TPVgCi2WQ8/8iC3c/2fpU9C/pG9u7l2IkgQYMpjaAF3PC33KIWL7UGUbtyxOwugB3fvzVplwt6uof7EpvyRCmrHgGxtBoE2e/ovzr2muuicHaJRQ7qVfhnqUJEYJOGSlUGafC2PJleTKkmSRLsBnP9jkH1spv93gM+U2U0neuN4oF7Lp4Jp1xLdYxnOluVkW0lO2VEVaUgn
